<a href="https://colab.research.google.com/github/DaDamola/AI-Learning/blob/master/HW4_Problem2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np 
import skimage.measure

class SizeError(Exception): #raised when the window size is larger than input 
  pass

def maxpooling2d(input_mat, s):
  x, y = input_mat.shape #get input dimensions
  pad, stride = 0, s

  try:
    if (x != y): #check when the input is square
      raise ValueError
    
    if s > x: #check when window size is larger than input
      raise SizeError
    
    #calculate rows and columns for output
    x = (x - s + 2 * pad) // stride + 1 
    y = (y - s + 2 * pad) // stride + 1 

    res = np.zeros((x,y)) 
    xoffset, yoffset = 0, 0

    #do max pooling 
    for row in range(x):
        yoffset = 0
        for col in range(y): 
          res[row][col] = np.max(input_mat[row+xoffset:row + s+xoffset, col+yoffset:col + s+yoffset]) 
          yoffset += 1
        xoffset += 1
        
         

 
    return res
  except ValueError:
    print("Input matrix must be a square.")
  except SizeError:
    print("Window size cannot be larger than input matrix.")


mat1 = np.array([[0,1,2,3,4],[5,6,7,8,9],[0,1,2,3,4],[5,6,7,8,9],[0,1,2,3,4]]) #5x5 matrix
mat2 = np.array([[0,1,2,3,4],[5,6,7,8,9],[0,1,2,3,4],[5,6,7,8,9]]) #4x5 matrix
mat3 = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
ma = np.array([[2,3],[0,1]])

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))


input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  #output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")






[[4. 2.]
 [2. 4.]]
Correct output!
[[4. 2. 5.]
 [2. 4. 5.]
 [1. 3. 2.]]
Correct output!


**Program Description:** This program accepts a square matrix and a window size, then performs the max pooling operation and returns a resultant matrix, otherwise it raises an exception.