<a href="https://colab.research.google.com/github/DaDamola/AI-Learning/blob/master/HW4_Problem1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import numpy as np 
from scipy import signal

class SizeError(Exception): #Raised when kernel is larger than input 
  pass

def conv2d(input_mat, kernel_mat):
  kernel_mat = np.rot90(kernel_mat, 2) #flip kernel 180 degrees in convolution

  m, n = kernel_mat.shape #get kernel dimensions
  x, y = input_mat.shape #get input dimensions
  pad, stride = 0, 1 

  try:
    if (m != n or x != y): #check when the kernel and input are square
      raise ValueError
    
    #calculate rows and columns for output
    x = (x - m + 2 * pad) // stride + 1 
    y = (y - m + 2 * pad) // stride + 1 

    if x < 1: #check when kernel is larger than input
      raise SizeError

    res = np.zeros((x,y)) 

    #do scanning convolution 
    for row in range(x):
        for col in range(y):
            res[row][col] = np.sum(input_mat[row:row + m, col:col + n] * kernel_mat) 
    
    return res
  except ValueError:
    print("Both matrices must be square.")
  except SizeError:
    print("The kernel cannot be larger than the input matrix.")
    



mat1 = np.array([[0,1,2,3,4],[5,6,7,8,9],[0,1,2,3,4],[5,6,7,8,9],[0,1,2,3,4]]) #5x5 matrix
mat2 = np.array([[0,1,2,3,4],[5,6,7,8,9],[0,1,2,3,4],[5,6,7,8,9]]) #4x5 matrix
mat3 = np.array([[1,0],[0,1]])
kernel1 = np.array([[1,0],[0,1]]) #2x2 filter
kernel2 = np.array([[1,0,0],[0,1,0],[0,0,1]]) #3x3 filter
kernel3 = np.array([[1,0,0],[0,1,0]]) #2x3 filter
kernel4 = np.array([[0,1,2,3,4],[5,6,7,8,9],[0,1,2,3,4],[5,6,7,8,9],[0,1,2,3,4]]) #5x5 matrix

print(conv2d(mat1, kernel2))
input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])



for i in range(len(input_mat)):
  # uncomment line for student code testing
  output_mat = conv2d(input_mat[i], kernel_mat[i])

  # uncomment lines below (and comment line above) for generating test cases.
  if input_mat[i].shape[0] < kernel_mat[i].shape[0]:
    output_mat = []
  else:
    output_mat = signal.convolve2d(input_mat[i], kernel_mat[i], mode='valid')

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")







[[ 8. 11. 14.]
 [13. 16. 19.]
 [ 8. 11. 14.]]
[[2 4 2]
 [4 2 4]
 [2 4 2]]
Correct output!

[[2 0 0]
 [0 2 0]
 [0 0 2]]
Correct output!

[[ 1 -1  0]
 [-1  1 -1]
 [ 0 -1  1]]
Correct output!

[[4]]
Correct output!

The kernel cannot be larger than the input matrix.
[]
Correct output!



**Program Description:** This program accepts two square matrices, performs the convolution operation and returns a resultant matrix, otherwise it raises an exception.
